### ISSUE TITLE
pull request for the cheat sheet (and how to have them merged?)

### ISSUE THREAD

**Issue by juliendorra** [openscad/openscad.github.com#46]
Hi, 
some time ago I found an omission in the cheatsheet, and added a pull request : 
https://github.com/openscad/openscad.github.com/pull/38

however, today I found an error, and when adding a pull-request, 
https://github.com/openscad/openscad.github.com/pull/45

 I found that the older pull-request was neither merged nor closed.

What is the process for pull-request on the cheat-sheet ? There is an incentive on the bottom of the page to edit it (good! as it is a key ressource) but then if there's no impact it's quite discouraging.

And the page is not without errors or omissions, compared to the wikibook and the IDE.

Can I help? (specifically on the cheat-sheet)

**Comment by kintel** [comment]
Sorry, I had overlooked your previous pull request.
If you want to help improving the cheat sheet that would be awesome! For now it's just a git repo so if you want I can add you the web team on github.

**Comment by t-paul** [comment]
I'm closing this as both pull requests were merged some time ago.
