### ISSUE TITLE
[suggestion] Enable https as default for https://[*.]openscad.org/

### ISSUE THREAD

**Issue by Rotzbua** [openscad/openscad.github.com#60]
According to the next release of Chrome 68 it would be good to think about https.
Chrome 68 will warn if http is used and maybe confuse some people.

Reference: https://blog.chromium.org/2018/02/a-secure-web-is-here-to-stay.html

![grafik](https://user-images.githubusercontent.com/7337347/43681177-2f791f54-984d-11e8-8e1a-d06c9b430379.png)

https would be also good for http://forum.openscad.org/ to avoid credential sniffing on public hotspots.

**Comment by MichaelAtOz** [comment]
> https would be also good for http://forum.openscad.org/ to avoid credential sniffing on public hotspots.

[Historically](http://support.nabble.com/HTTPS-SSL-urgent-tp7594627p7598046.html) nabble did not support HTTPS and said they never would.
This appears to [have changed](http://support.nabble.com/HTTPS-Protocol-td7600829.html), but it looks a [bit flakey](http://support.nabble.com/Https-Protocol-Request-td7600969i60.html).

It seems we would need a SSL certificate for the subdomain.

But I think it should wait until there is a clear procedure for the change, reading other posts it does seem a bit hairy ATM.

**Comment by Rotzbua** [comment]
> It seems we would need a SSL certificate for the subdomain.

They would automatically issue a certificate by lets encrypt, so you do not have to buy a certificate.

> But I think it should wait until there is a clear procedure for the change, reading other posts it does seem a bit hairy ATM.

I see. Let them work on it until it is stable.


The main openscad page should be usable under https without any restrictions (e.g. mixed content)  with my pr #58 #59 #61 #62. Currently www.openscad.org do work under https but do not show all donate buttons.

At the moment, github does not support https on the redirect page openscad.org. It must be manually configured by a provider.
https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

**Comment by kintel** [comment]
Everything except the forum should be using https now.

**Comment by t-paul** [comment]
I've updated a couple of more links so the mixed-content should be mostly gone. I'll create a new issue specifically for the forum so we can revist that some time later.
