### ISSUE TITLE
Appcast XML Incorrect

### ISSUE THREAD

**Issue by dcoobs** [openscad/openscad.github.com#72]
The URLs in the appcast.xml file appear to be incorrect and are throwing 404 errors.

![404](https://user-images.githubusercontent.com/12276948/55181991-d5f4af80-515a-11e9-8df6-2506d60e385e.PNG)

^^  https://files.openscad.org/OpenSCAD-2019.01-RC4.dmg

**Comment by dcoobs** [comment]
@kintel Wasn't sure if there was a better place to post this issue?

**Comment by kintel** [comment]
This is a good place. This is a script mishap.
