### ISSUE TITLE
Add German site https://3d-spielplatz.de to https://www.openscad.org/documentation.html?

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [openscad/openscad.github.com#86]
Firstly, thanks for OpenSCAD! It's made my 3D design experience so much better!

I've recently begun to create a 3D design- and -print-website called [https://www.3d-spielplatz.de](https://www.3d-spielplatz.de). 
Currently most of it's content is in German and all of the design examples are using OpenSCAD.

If you believe a link to on https://www.openscad.org/documentation.html might be of value to some of your openscad.org visitors I'd love to do a PR.

**Comment by t-paul** [comment]
I think getting some more recent content on there would be good. It should be obvious that it's German only but I see no issue with linking to language specific sites.

@kintel what's your opinion about this?

**Comment by kintel** [comment]
I’m all for it!

**Comment by t-paul** [comment]
Great, one suggestion though... It might be useful to clarify the intention regarding use of the examples. I just found the notice that even any use of the OpenSCAD code would need written agreement. I see no point in adding the site with that rule.

**Comment by HaraldMuehlhoffCC** [comment]
Thank you both very much!

@t-paul, you're referring  to https://3d-spielplatz.de/de/impressum (Copyright section), aren't you ... ;) Somebody actually reading the imprint, call me impressed! ;)

I've just uploaded a clarified version of this page; the original version made not much sense for a site like 3d-spielplatz.de. I will try to make licensing of the code even clearer in the future. So thank you for bringing this to my attention.

**Comment by t-paul** [comment]
Yep, I was looking for how the OpenSCAD code is licensed and found only the that impressum note. The change to non-commercial use seems fine and commonly understood.
Do you have some logo for the site? Feel free to add a section to the documentation page similar to the other entries. Maybe as 2nd after the tutorial by Jeremie Francois.

**Comment by HaraldMuehlhoffCC** [comment]
Great! Actually I do have a simple logo that's currently only used for the PWA version of the site. Not sure whether it fits in with the other images on the documentation page though. If it's ok for you I just might make a screenshot of matching proportions & use that instead?

https://3d-spielplatz.de/icons/icon-256x256.png

**Comment by t-paul** [comment]
Sure, we can always update later.

**Comment by HaraldMuehlhoffCC** [comment]
I've just created the PR https://github.com/openscad/openscad.github.com/pull/87. Thanks!
