### ISSUE TITLE
Related projects dicussion

### ISSUE THREAD

**Issue by Irev-Dev** [openscad/openscad.github.com#94]
Hey just wanted to open up a discussion about the related projects sections the about page of the website.

I've been putting together list of all code-cad projects I can find [here](https://kurthutten.com/blog/curated-code-cad), and also on [Github](https://github.com/Irev-Dev/curated-code-cad). And at first the related projects section on openscad.org was a useful resource but it does seem a little out of date. It's incomplete (which it states) but also http://ww7.openscad.net/?z seems to be a dead link. I had been thinking about putting up a pull request to update the section with all of the ones I've found. But I thought it would be best to check with with an issue first. Because updating the list won't stop it from going stale again and I'm not sure if all of the projects in my list were "inspired" by OpenScad (realistically I'm sure they all were) or if that even matters. One alternative is to link to my list since I do plan on keeping it up to date.

Any preference? or an option I haven't thought of?

Cheers,
Kurt

**Comment by mmiscool** [comment]
Hello. I was interested in the possibility of including https://OpenSCAD.cloud as a link on this section. It is using the new WASM port of OpenSCAD done by DSchroer https://github.com/DSchroer/openscad-wasm and is live for folks to use.

**Comment by t-paul** [comment]
@mmiscool, done.

**Comment by mmiscool** [comment]
@t-paul Wow. That was fast. Thanks!

**Comment by t-paul** [comment]
Closing as there isn't much happening. I think the related projects should simply have *some* sort of relation to OpenSCAD, but not just be any Code CAD.
